apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-agent-wal
  namespace: prometheus
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi