apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efkstack
data:
  fluent.conf: |
    ############################################################
    # 1) Fluent Bit → Fluentd 입력 (forward)
    ############################################################
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    ############################################################
    # 2) 서비스 애플리케이션 로그 → Kafka 전송 (service-topic)
    ############################################################
    <match service.application.log>
      @type kafka2
      brokers b-1.sologmskcluster2.tak97t.c4.kafka.ap-northeast-2.amazonaws.com:9092 
      topic service-topic
      use_event_time true

      <format>
        @type json
      </format>

      <buffer>
        @type memory
        flush_interval 1s
        flush_at_shutdown true
        flush_thread_count 2
        chunk_limit_size 1m
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>

    ############################################################
    # 3-1) kmsg  애플리케이션 로그 → Kafka 전송 (system-kmsg-topic)
    ############################################################
    <match system.kmsg.log>
      @type kafka2
      brokers b-1.sologmskcluster2.tak97t.c4.kafka.ap-northeast-2.amazonaws.com:9092 
      topic system-kmsg-topic
      use_event_time true

      <format>
        @type json
      </format>

      <buffer>
        @type memory
        flush_interval 1s
        flush_at_shutdown true
        flush_thread_count 2
        chunk_limit_size 1m
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>

    ############################################################
    # 3-2) 시스템 로그 → AUTH (system-auth-topic)
    ############################################################
    <filter system.auth.log>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type regexp
        expression /^(?<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d+\+\d{2}:\d{2})\s+(?<host>\S+)\s+sshd\[(?<pid>\d+)\]:\s+(?<auth_result>Accepted|Failed)\s+password\s+for\s+(?:invalid user\s+)?(?<user>\S+)\s+from\s+(?<ip>[0-9\.]+)\s+port\s+(?<port>\d+)\s+ssh2$/
      </parse>
    </filter>

    <match system.auth.log>
      @type kafka2
      brokers b-1.sologmskcluster2.tak97t.c4.kafka.ap-northeast-2.amazonaws.com:9092 
      topic system-auth-topic
      use_event_time true

      <format>
        @type json
      </format>

      <buffer>
        @type memory
        flush_interval 1s
        flush_at_shutdown true
        flush_thread_count 2
        chunk_limit_size 1m
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>

    ############################################################
    # 4) 매칭 안 된 나머지 (디버깅용)
    ############################################################
    <match **>
      @type stdout
    </match>