apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-inputgen-deployment
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      system: auth
  template:
    metadata:
      labels:
        system: auth
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: auth-inputgen
          image: kyla333/inputgen4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"